### ISSUE TITLE
Typo in version number on main page

### ISSUE THREAD

**Issue by rkottmann** [docbook/defguide#103]
On page https://tdg.docbook.org/ in section "DocBook 5: The Definitive Guide" there is a typo: I guess 1.5.3 should be 5.1.3 . See screenshot.

![grafik](https://github.com/docbook/defguide/assets/36152255/97e5240f-f65b-4a31-99bf-4a0472a0acb4)

**Comment by SamB** [comment]
I think that typo is actually in the source, because it shows up in the book itself.

*[looking noises]*

Well, technically it's not actually *embedded* in the book source code, just this line in the build configuration https://github.com/docbook/defguide/blob/b60151b329bb46ba25044b72e60902a2ddca1a94/gradle.properties#L9

(That permalink was to https://github.com/docbook/defguide/blob/docbook-5.1/gradle.properties as of just now.)

And yeah, given the form of the other versions, that looks very much like a dyslexia or [`M-t` (`transpose-words`)](https://www.gnu.org/software/emacs/manual/html_node/emacs/Transpose.html#index-transpose_002dwords) moment. (Would it be reasonable to release the fix as 5.1.3, or would it need bumping to 5.1.4?)

**Comment by ndw** [comment]
I don't think that's a typo. The version of the guide for DocBook 5.1 is "1.5.3". The version numbering is a bit weird, I admit, but that's consistent with the scheme we were using in the 5.1 days.
